<?php
// backend/import-movies.php

header("Content-Type: application/json");

$dbPath = __DIR__ . '/database.sqlite';

try {
    $db = new PDO("sqlite:$dbPath");
    $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    
    // Check if movies already exist
    $checkStmt = $db->query("SELECT COUNT(*) as count FROM movies");
    $result = $checkStmt->fetch(PDO::FETCH_ASSOC);
    
    if ($result['count'] > 0) {
        echo json_encode([
            'success' => false,
            'message' => "Movies already exist in database. Found {$result['count']} movies.",
            'action' => 'Run this script only once or clear the database first.'
        ]);
        exit();
    }
    
    // Your movie data with metadata
    $movies = [
        [
            "id" => "1",
            "title" => "Black Widow 2021",
            "slug" => "black-widow-2021",
            "description" => "Natasha Romanoff confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises.",
            "poster" => "/media/thumbnails/posters/black-widow.jpg",
            "backdrop" => "/media/thumbnails/backdrops/black-widow.jpg",
            "video" => "/media/movies/Black-Widow-2021.mp4",
            "duration" => 134,
            "categoryId" => "1",
            "published" => 1,
            "year" => 2021,
            "rating" => 6.7,
            "featured" => 1,
            "badge" => "Action Adventure",
            "genres" => ["Action", "Adventure", "Sci-Fi"],
            "cast_list" => ["Scarlett Johansson", "Florence Pugh", "David Harbour", "Rachel Weisz"],
            "director" => "Cate Shortland",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "2",
            "title" => "Blue Beetle 2023",
            "slug" => "blue-beetle-2023",
            "description" => "An alien relic chooses Jaime Reyes to be its symbiotic host, bestowing the teenager with a suit of armor that's capable of extraordinary and unpredictable powers.",
            "poster" => "/media/thumbnails/posters/blue-beetle.jpg",
            "backdrop" => "/media/thumbnails/backdrops/blue-beetle.jpg",
            "video" => "/media/movies/Blue-Beetle-2023.mp4",
            "duration" => 127,
            "categoryId" => "1",
            "published" => 1,
            "year" => 2023,
            "rating" => 6.1,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Action", "Adventure", "Sci-Fi", "Comedy"],
            "cast_list" => ["Xolo Maridueña", "Bruna Marquezine", "Becky G", "George Lopez"],
            "director" => "Angel Manuel Soto",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "3",
            "title" => "Casino Royale",
            "slug" => "casino-royale",
            "description" => "After earning 00 status and a licence to kill, Secret Agent James Bond sets out on his first mission as 007.",
            "poster" => "/media/thumbnails/posters/casino-royale.jpg",
            "backdrop" => "/media/thumbnails/backdrops/casino-royale.jpg",
            "video" => "/media/movies/Casino-Royale.mp4",
            "duration" => 144,
            "categoryId" => "2",
            "published" => 1,
            "year" => 2006,
            "rating" => 8.0,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Action", "Adventure", "Thriller"],
            "cast_list" => ["Daniel Craig", "Eva Green", "Mads Mikkelsen", "Judi Dench"],
            "director" => "Martin Campbell",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "4",
            "title" => "Chef 2014",
            "slug" => "chef-2014",
            "description" => "A head chef quits his restaurant job and buys a food truck in an effort to reclaim his creative promise, while piecing back together his estranged family.",
            "poster" => "/media/thumbnails/posters/chef.jpg",
            "backdrop" => "/media/thumbnails/backdrops/chef.jpg",
            "video" => "/media/movies/Chef-2014.mp4",
            "duration" => 114,
            "categoryId" => "4",
            "published" => 1,
            "year" => 2014,
            "rating" => 7.3,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Comedy", "Drama", "Adventure"],
            "cast_list" => ["Jon Favreau", "Sofia Vergara", "John Leguizamo", "Scarlett Johansson"],
            "director" => "Jon Favreau",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "R"
        ],
        [
            "id" => "5",
            "title" => "Equalizer",
            "slug" => "equalizer",
            "description" => "A man who believes he has put his mysterious past behind him cannot stand idly by when he meets a young girl under the control of ultra-violent Russian gangsters.",
            "poster" => "/media/thumbnails/posters/equalizer.jpg",
            "backdrop" => "/media/thumbnails/backdrops/equalizer.jpg",
            "video" => "/media/movies/equalizer.mp4",
            "duration" => 132,
            "categoryId" => "6",
            "published" => 1,
            "year" => 2014,
            "rating" => 7.2,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Action", "Crime", "Thriller"],
            "cast_list" => ["Denzel Washington", "Marton Csokas", "Chloë Grace Moretz", "David Harbour"],
            "director" => "Antoine Fuqua",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "R"
        ],
        [
            "id" => "6",
            "title" => "Eternals",
            "slug" => "eternals",
            "description" => "The Eternals, a race of immortal beings with superhuman powers who have secretly lived on Earth for thousands of years, reunite to battle the evil Deviants.",
            "poster" => "/media/thumbnails/posters/eternals.jpg",
            "backdrop" => "/media/thumbnails/backdrops/eternals.jpg",
            "video" => "/media/movies/Eternals.mkv",
            "duration" => 156,
            "categoryId" => "1",
            "published" => 1,
            "year" => 2021,
            "rating" => 6.3,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Action", "Adventure", "Sci-Fi"],
            "cast_list" => ["Gemma Chan", "Richard Madden", "Angelina Jolie", "Salma Hayek"],
            "director" => "Chloé Zhao",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "7",
            "title" => "I Robot",
            "slug" => "i-robot",
            "description" => "In 2035, a technophobic detective investigates a crime that may have been perpetrated by a robot, which leads to a larger threat to humanity.",
            "poster" => "/media/thumbnails/posters/i-robot.jpg",
            "backdrop" => "/media/thumbnails/backdrops/i-robot.jpg",
            "video" => "/media/movies/i-robot.mp4",
            "duration" => 115,
            "categoryId" => "23",
            "published" => 1,
            "year" => 2004,
            "rating" => 7.1,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Action", "Sci-Fi", "Thriller"],
            "cast_list" => ["Will Smith", "Bridget Moynahan", "Bruce Greenwood", "James Cromwell"],
            "director" => "Alex Proyas",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "8",
            "title" => "Joker 2019",
            "slug" => "joker-2019",
            "description" => "Arthur Fleck, a party clown, leads an impoverished life with his ill mother. However, when society shuns him and brings him down, he decides to embrace a life of chaos and crime.",
            "poster" => "/media/thumbnails/posters/joker.jpg",
            "backdrop" => "/media/thumbnails/backdrops/joker.jpg",
            "video" => "/media/movies/Joker-2019.mp4",
            "duration" => 122,
            "categoryId" => "1",
            "published" => 1,
            "year" => 2019,
            "rating" => 8.4,
            "featured" => 1,
            "badge" => "Award-Winning Drama",
            "genres" => ["Crime", "Drama", "Thriller"],
            "cast_list" => ["Joaquin Phoenix", "Robert De Niro", "Zazie Beetz", "Frances Conroy"],
            "director" => "Todd Phillips",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "R"
        ],
        [
            "id" => "9",
            "title" => "Julie and Julia",
            "slug" => "julie-and-julia",
            "description" => "Julia Child's life and cookbook inspire a young woman in 2002 New York to cook all 524 recipes in one year, blogging about her progress.",
            "poster" => "/media/thumbnails/posters/julie-and-julia.jpg",
            "backdrop" => "/media/thumbnails/backdrops/julie-and-julia.jpg",
            "video" => "/media/movies/Julie-and-Julia.mp4",
            "duration" => 123,
            "categoryId" => "4",
            "published" => 1,
            "year" => 2009,
            "rating" => 7.0,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Biography", "Drama", "Romance"],
            "cast_list" => ["Meryl Streep", "Amy Adams", "Stanley Tucci", "Chris Messina"],
            "director" => "Nora Ephron",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "10",
            "title" => "Just Laugh Out Load",
            "slug" => "just-laugh-out-load",
            "description" => "A hilarious comedy that brings laughter and joy through a series of side-splitting situations and unforgettable characters.",
            "poster" => "/media/thumbnails/posters/just-laugh.jpg",
            "backdrop" => "/media/thumbnails/backdrops/just-laugh.jpg",
            "video" => "/media/movies/Just%20laugh%20Out%20Load.mp4",
            "duration" => 85,
            "categoryId" => "4",
            "published" => 1,
            "year" => 2024,
            "rating" => 6.0,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Comedy"],
            "cast_list" => ["Comedy Ensemble"],
            "director" => "Comedy Director",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "11",
            "title" => "Just Laugh Out Load 2",
            "slug" => "just-laugh-out-load-2",
            "description" => "More hilarious comedy sketches for your entertainment.",
            "poster" => "/media/thumbnails/posters/just-laugh-2.jpg",
            "backdrop" => "/media/thumbnails/backdrops/just-laugh-2.jpg",
            "video" => "/media/movies/Just%20laugh%20Out%20Load%202.mp4",
            "duration" => 10,
            "categoryId" => "4",
            "published" => 1,
            "year" => 2024,
            "rating" => 5.5,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Comedy"],
            "cast_list" => ["Comedy Ensemble"],
            "director" => "Comedy Director",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "12",
            "title" => "Just Laugh Out Load 3",
            "slug" => "just-laugh-out-load-3",
            "description" => "Comedy sketches that will make you laugh out loud.",
            "poster" => "/media/thumbnails/posters/just-laugh-3.jpg",
            "backdrop" => "/media/thumbnails/backdrops/just-laugh-3.jpg",
            "video" => "/media/movies/Just%20laugh%20Out%20Load%203.mp4",
            "duration" => 12,
            "categoryId" => "4",
            "published" => 1,
            "year" => 2024,
            "rating" => 5.5,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Comedy"],
            "cast_list" => ["Comedy Ensemble"],
            "director" => "Comedy Director",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "13",
            "title" => "Just Laugh Out Load 4",
            "slug" => "just-laugh-out-load-4",
            "description" => "Short comedy clips for quick entertainment.",
            "poster" => "/media/thumbnails/posters/just-laugh-4.jpg",
            "backdrop" => "/media/thumbnails/backdrops/just-laugh-4.jpg",
            "video" => "/media/movies/Just%20laugh%20Out%20Load%204.mp4",
            "duration" => 7,
            "categoryId" => "4",
            "published" => 1,
            "year" => 2024,
            "rating" => 5.5,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Comedy"],
            "cast_list" => ["Comedy Ensemble"],
            "director" => "Comedy Director",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "14",
            "title" => "Just Laugh Out Load 5",
            "slug" => "just-laugh-out-load-5",
            "description" => "More funny moments and comedy sketches.",
            "poster" => "/media/thumbnails/posters/just-laugh-5.jpg",
            "backdrop" => "/media/thumbnails/backdrops/just-laugh-5.jpg",
            "video" => "/media/movies/Just%20laugh%20Out%20Load%205.mp4",
            "duration" => 6,
            "categoryId" => "4",
            "published" => 1,
            "year" => 2024,
            "rating" => 5.5,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Comedy"],
            "cast_list" => ["Comedy Ensemble"],
            "director" => "Comedy Director",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "15",
            "title" => "Just Laugh Out Load 6",
            "slug" => "just-laugh-out-load-6",
            "description" => "The final collection of comedy sketches.",
            "poster" => "/media/thumbnails/posters/just-laugh-6.jpg",
            "backdrop" => "/media/thumbnails/backdrops/just-laugh-6.jpg",
            "video" => "/media/movies/Just%20laugh%20Out%20Load%206.mp4",
            "duration" => 9,
            "categoryId" => "4",
            "published" => 1,
            "year" => 2024,
            "rating" => 5.5,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Comedy"],
            "cast_list" => ["Comedy Ensemble"],
            "director" => "Comedy Director",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "16",
            "title" => "Legend",
            "slug" => "legend",
            "description" => "Identical twin brothers Reggie and Ronnie Kray, two of the most notorious gangsters in British history, rule the London underworld during the 1960s.",
            "poster" => "/media/thumbnails/posters/legend.jpg",
            "backdrop" => "/media/thumbnails/backdrops/legend.jpg",
            "video" => "/media/movies/Legend.mp4",
            "duration" => 132,
            "categoryId" => "3",
            "published" => 1,
            "year" => 2015,
            "rating" => 6.9,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Biography", "Crime", "Drama"],
            "cast_list" => ["Tom Hardy", "Emily Browning", "Taron Egerton", "Paul Anderson"],
            "director" => "Brian Helgeland",
            "country" => "UK",
            "language" => "English",
            "content_rating" => "R"
        ],
        [
            "id" => "17",
            "title" => "Martian",
            "slug" => "martian",
            "description" => "An astronaut becomes stranded on Mars after his team assume him dead, and must rely on his ingenuity to find a way to signal to Earth that he is alive.",
            "poster" => "/media/thumbnails/posters/martian.jpg",
            "backdrop" => "/media/thumbnails/backdrops/martian.jpg",
            "video" => "/media/movies/Martian.mp4",
            "duration" => 144,
            "categoryId" => "23",
            "published" => 1,
            "year" => 2015,
            "rating" => 8.0,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Adventure", "Drama", "Sci-Fi"],
            "cast_list" => ["Matt Damon", "Jessica Chastain", "Kristen Wiig", "Jeff Daniels"],
            "director" => "Ridley Scott",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "18",
            "title" => "Moana 2",
            "slug" => "moana-2",
            "description" => "In ancient Polynesia, a young girl embarks on a daring mission to save her people after a curse threatens their island.",
            "poster" => "/media/thumbnails/posters/moana-2.jpg",
            "backdrop" => "/media/thumbnails/backdrops/moana-2.jpg",
            "video" => "/media/movies/Moana2.mp4",
            "duration" => 107,
            "categoryId" => "1",
            "published" => 1,
            "year" => 2024,
            "rating" => 7.6,
            "featured" => 1,
            "badge" => "Animated Adventure",
            "genres" => ["Animation", "Adventure", "Comedy", "Family"],
            "cast_list" => ["Auli'i Cravalho", "Dwayne Johnson", "Rachel House", "Temuera Morrison"],
            "director" => "Ron Clements, John Musker",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG"
        ],
        [
            "id" => "19",
            "title" => "Pearl Harbor",
            "slug" => "pearl-harbor",
            "description" => "A tale of war and romance in the Pacific during World War II, following two lifelong friends and a beautiful nurse who are caught up in the deadly surprise attack on Pearl Harbor.",
            "poster" => "/media/thumbnails/posters/pearl-harbor.jpg",
            "backdrop" => "/media/thumbnails/backdrops/pearl-harbor.jpg",
            "video" => "/media/movies/Pearl-Harbor.mp4",
            "duration" => 183,
            "categoryId" => "3",
            "published" => 1,
            "year" => 2001,
            "rating" => 6.2,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Action", "Drama", "History", "Romance"],
            "cast_list" => ["Ben Affleck", "Josh Hartnett", "Kate Beckinsale", "Cuba Gooding Jr."],
            "director" => "Michael Bay",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "20",
            "title" => "Pirates",
            "slug" => "pirates",
            "description" => "Jack Sparrow, a freewheeling 18th-century pirate, joins forces with Elizabeth Swann and Will Turner to reclaim his beloved ship, the Black Pearl.",
            "poster" => "/media/thumbnails/posters/pirates.jpg",
            "backdrop" => "/media/thumbnails/backdrops/pirates.jpg",
            "video" => "/media/movies/Pirates.mp4",
            "duration" => 143,
            "categoryId" => "3",
            "published" => 1,
            "year" => 2003,
            "rating" => 8.1,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Action", "Adventure", "Comedy", "Fantasy"],
            "cast_list" => ["Johnny Depp", "Orlando Bloom", "Keira Knightley", "Geoffrey Rush"],
            "director" => "Gore Verbinski",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "21",
            "title" => "Scare 01",
            "slug" => "scare-01",
            "description" => "A terrifying horror experience that will keep you on edge.",
            "poster" => "/media/thumbnails/posters/scare-01.jpg",
            "backdrop" => "/media/thumbnails/backdrops/scare-01.jpg",
            "video" => "/media/movies/scare01.mp4",
            "duration" => 5,
            "categoryId" => "30",
            "published" => 1,
            "year" => 2024,
            "rating" => 4.5,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Horror", "Thriller"],
            "cast_list" => ["Horror Ensemble"],
            "director" => "Horror Director",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "R"
        ],
        [
            "id" => "22",
            "title" => "Scare 02",
            "slug" => "scare-02",
            "description" => "More horror and suspense in this chilling installment.",
            "poster" => "/media/thumbnails/posters/scare-02.jpg",
            "backdrop" => "/media/thumbnails/backdrops/scare-02.jpg",
            "video" => "/media/movies/scare02.mp4",
            "duration" => 8,
            "categoryId" => "30",
            "published" => 1,
            "year" => 2024,
            "rating" => 4.5,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Horror", "Thriller"],
            "cast_list" => ["Horror Ensemble"],
            "director" => "Horror Director",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "R"
        ],
        [
            "id" => "23",
            "title" => "Scare 03",
            "slug" => "scare-03",
            "description" => "The terror continues with more jump scares and suspense.",
            "poster" => "/media/thumbnails/posters/scare-03.jpg",
            "backdrop" => "/media/thumbnails/backdrops/scare-03.jpg",
            "video" => "/media/movies/scare03.mp4",
            "duration" => 7,
            "categoryId" => "30",
            "published" => 1,
            "year" => 2024,
            "rating" => 4.5,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Horror", "Thriller"],
            "cast_list" => ["Horror Ensemble"],
            "director" => "Horror Director",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "R"
        ],
        [
            "id" => "24",
            "title" => "Scare 04",
            "slug" => "scare-04",
            "description" => "Horror anthology that will send chills down your spine.",
            "poster" => "/media/thumbnails/posters/scare-04.jpg",
            "backdrop" => "/media/thumbnails/backdrops/scare-04.jpg",
            "video" => "/media/movies/scare04.mp4",
            "duration" => 6,
            "categoryId" => "30",
            "published" => 1,
            "year" => 2024,
            "rating" => 4.5,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Horror", "Thriller"],
            "cast_list" => ["Horror Ensemble"],
            "director" => "Horror Director",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "R"
        ],
        [
            "id" => "25",
            "title" => "Scare 05",
            "slug" => "scare-05",
            "description" => "The fear intensifies in this horror collection.",
            "poster" => "/media/thumbnails/posters/scare-05.jpg",
            "backdrop" => "/media/thumbnails/backdrops/scare-05.jpg",
            "video" => "/media/movies/scare05.mp4",
            "duration" => 9,
            "categoryId" => "30",
            "published" => 1,
            "year" => 2024,
            "rating" => 4.5,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Horror", "Thriller"],
            "cast_list" => ["Horror Ensemble"],
            "director" => "Horror Director",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "R"
        ],
        [
            "id" => "26",
            "title" => "Scare 06",
            "slug" => "scare-06",
            "description" => "The final chapter in the horror series.",
            "poster" => "/media/thumbnails/posters/scare-06.jpg",
            "backdrop" => "/media/thumbnails/backdrops/scare-06.jpg",
            "video" => "/media/movies/scare06.mp4",
            "duration" => 10,
            "categoryId" => "30",
            "published" => 1,
            "year" => 2024,
            "rating" => 4.5,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Horror", "Thriller"],
            "cast_list" => ["Horror Ensemble"],
            "director" => "Horror Director",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "R"
        ],
        [
            "id" => "27",
            "title" => "Shang Chi",
            "slug" => "shang-chi",
            "description" => "Shang-Chi, the master of martial arts, must confront his past and face the mysterious Ten Rings organization.",
            "poster" => "/media/thumbnails/posters/shang-chi.jpg",
            "backdrop" => "/media/thumbnails/backdrops/shang-chi.jpg",
            "video" => "/media/movies/Shang-Chi.mkv",
            "duration" => 132,
            "categoryId" => "1",
            "published" => 1,
            "year" => 2021,
            "rating" => 7.4,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Action", "Adventure", "Fantasy"],
            "cast_list" => ["Simu Liu", "Awkwafina", "Tony Leung", "Meng'er Zhang"],
            "director" => "Destin Daniel Cretton",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "28",
            "title" => "Spider-Man 3",
            "slug" => "spider-man-3",
            "description" => "Peter Parker has finally managed to strike a balance between his devotion to M.J. and his duties as a superhero. But there is a new villain, and with the return of an old enemy, Peter's life is turned upside down.",
            "poster" => "/media/thumbnails/posters/spider-man-3.jpg",
            "backdrop" => "/media/thumbnails/backdrops/spider-man-3.jpg",
            "video" => "/media/movies/Spider-Man-3.mp4",
            "duration" => 139,
            "categoryId" => "1",
            "published" => 1,
            "year" => 2007,
            "rating" => 6.3,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Action", "Adventure", "Sci-Fi"],
            "cast_list" => ["Tobey Maguire", "Kirsten Dunst", "James Franco", "Thomas Haden Church"],
            "director" => "Sam Raimi",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "29",
            "title" => "Spider-Man Into The Spider-Verse",
            "slug" => "spider-man-into-the-spider-verse",
            "description" => "Teen Miles Morales becomes the Spider-Man of his reality, crossing paths with five counterparts from other dimensions to stop a threat for all realities.",
            "poster" => "/media/thumbnails/posters/spider-verse.jpg",
            "backdrop" => "/media/thumbnails/backdrops/spider-verse.jpg",
            "video" => "/media/movies/Spider-Man-Into-The-Spider-Verse.mp4",
            "duration" => 117,
            "categoryId" => "1",
            "published" => 1,
            "year" => 2018,
            "rating" => 8.4,
            "featured" => 1,
            "badge" => "Animated Masterpiece",
            "genres" => ["Animation", "Action", "Adventure", "Comedy", "Sci-Fi"],
            "cast_list" => ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld", "Mahershala Ali"],
            "director" => "Bob Persichetti, Peter Ramsey, Rodney Rothman",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG"
        ],
        [
            "id" => "30",
            "title" => "The Amazing Spider-Man 2",
            "slug" => "the-amazing-spider-man-2",
            "description" => "Peter Parker faces new challenges while trying to maintain his relationship with Gwen Stacy. Meanwhile, a new villain, Electro, emerges.",
            "poster" => "/media/thumbnails/posters/amazing-spider-man-2.jpg",
            "backdrop" => "/media/thumbnails/backdrops/amazing-spider-man-2.jpg",
            "video" => "/media/movies/The-Amazing-Spider-Man-2.mp4",
            "duration" => 142,
            "categoryId" => "1",
            "published" => 1,
            "year" => 2014,
            "rating" => 6.6,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Action", "Adventure", "Sci-Fi"],
            "cast_list" => ["Andrew Garfield", "Emma Stone", "Jamie Foxx", "Dane DeHaan"],
            "director" => "Marc Webb",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "31",
            "title" => "The Hunger Games",
            "slug" => "the-hunger-games",
            "description" => "Katniss Everdeen voluntarily takes her younger sister's place in the Hunger Games, a televised fight to the death.",
            "poster" => "/media/thumbnails/posters/hunger-games.jpg",
            "backdrop" => "/media/thumbnails/backdrops/hunger-games.jpg",
            "video" => "/media/movies/The-Hunger-Games.mp4",
            "duration" => 142,
            "categoryId" => "2",
            "published" => 1,
            "year" => 2012,
            "rating" => 7.2,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Action", "Adventure", "Sci-Fi", "Drama"],
            "cast_list" => ["Jennifer Lawrence", "Josh Hutcherson", "Liam Hemsworth", "Woody Harrelson"],
            "director" => "Gary Ross",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "32",
            "title" => "The Intern",
            "slug" => "the-intern",
            "description" => "A seventy-year-old widower applies to become an intern at an online fashion startup, where he forms an unexpected friendship with the young CEO.",
            "poster" => "/media/thumbnails/posters/the-intern.jpg",
            "backdrop" => "/media/thumbnails/backdrops/the-intern.jpg",
            "video" => "/media/movies/The-Intern.mp4",
            "duration" => 121,
            "categoryId" => "4",
            "published" => 1,
            "year" => 2015,
            "rating" => 7.1,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Comedy", "Drama"],
            "cast_list" => ["Robert De Niro", "Anne Hathaway", "Rene Russo", "Anders Holm"],
            "director" => "Nancy Meyers",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "33",
            "title" => "The Longest Yard",
            "slug" => "the-longest-yard",
            "description" => "A former NFL quarterback serving time in prison is forced to lead his fellow inmates in a football game against the prison guards.",
            "poster" => "/media/thumbnails/posters/longest-yard.jpg",
            "backdrop" => "/media/thumbnails/backdrops/longest-yard.jpg",
            "video" => "/media/movies/The-Longest-Yard.mp4",
            "duration" => 113,
            "categoryId" => "4",
            "published" => 1,
            "year" => 2005,
            "rating" => 6.4,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Comedy", "Crime", "Sport"],
            "cast_list" => ["Adam Sandler", "Chris Rock", "James Cromwell", "Nelly"],
            "director" => "Peter Segal",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "34",
            "title" => "The Marvels",
            "slug" => "the-marvels",
            "description" => "Carol Danvers, Monica Rambeau, and Kamala Khan must work together to save the universe when their powers become entangled.",
            "poster" => "/media/thumbnails/posters/the-marvels.jpg",
            "backdrop" => "/media/thumbnails/backdrops/the-marvels.jpg",
            "video" => "/media/movies/The-Marvels.mp4",
            "duration" => 105,
            "categoryId" => "1",
            "published" => 1,
            "year" => 2023,
            "rating" => 5.5,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Action", "Adventure", "Sci-Fi"],
            "cast_list" => ["Brie Larson", "Teyonah Parris", "Iman Vellani", "Samuel L. Jackson"],
            "director" => "Nia DaCosta",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "35",
            "title" => "The Peanut Butter Falcon",
            "slug" => "the-peanut-butter-falcon",
            "description" => "Zak runs away from a care home to pursue his dream of becoming a professional wrestler, meeting a small-time outlaw on the run.",
            "poster" => "/media/thumbnails/posters/peanut-butter-falcon.jpg",
            "backdrop" => "/media/thumbnails/backdrops/peanut-butter-falcon.jpg",
            "video" => "/media/movies/The%20Peanut%20Butter%20Falcon.mkv",
            "duration" => 97,
            "categoryId" => "4",
            "published" => 1,
            "year" => 2019,
            "rating" => 7.6,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Adventure", "Comedy", "Drama"],
            "cast_list" => ["Zack Gottsagen", "Shia LaBeouf", "Dakota Johnson", "Bruce Dern"],
            "director" => "Tyler Nilson, Michael Schwartz",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "36",
            "title" => "The Pursuit Of Happyness",
            "slug" => "the-pursuit-of-happyness",
            "description" => "A struggling salesman takes custody of his son as he's poised to begin a life-changing professional endeavor, facing homelessness and despair.",
            "poster" => "/media/thumbnails/posters/pursuit-of-happyness.jpg",
            "backdrop" => "/media/thumbnails/backdrops/pursuit-of-happyness.jpg",
            "video" => "/media/movies/The%20Pursuit%20Of%20Happyness.mp4",
            "duration" => 117,
            "categoryId" => "4",
            "published" => 1,
            "year" => 2006,
            "rating" => 8.0,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Biography", "Drama"],
            "cast_list" => ["Will Smith", "Jaden Smith", "Thandie Newton", "Brian Howe"],
            "director" => "Gabriele Muccino",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "37",
            "title" => "The Secret Life of Walter Mitty",
            "slug" => "the-secret-life-of-walter-mitty",
            "description" => "A day-dreamer escapes his anonymous life by disappearing into a world of fantasies, and when his job is threatened, he takes action in the real world.",
            "poster" => "/media/thumbnails/posters/walter-mitty.jpg",
            "backdrop" => "/media/thumbnails/backdrops/walter-mitty.jpg",
            "video" => "/media/movies/The%20Secret%20Life%20of%20Walter%20Mitty%202013.mp4",
            "duration" => 114,
            "categoryId" => "4",
            "published" => 1,
            "year" => 2013,
            "rating" => 7.3,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Adventure", "Comedy", "Drama"],
            "cast_list" => ["Ben Stiller", "Kristen Wiig", "Adam Scott", "Sean Penn"],
            "director" => "Ben Stiller",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG"
        ],
        [
            "id" => "38",
            "title" => "The Texas Chainsaw Massacre",
            "slug" => "the-texas-chainsaw-massacre",
            "description" => "A group of friends traveling through rural Texas fall prey to a family of cannibalistic psychopaths, including the chainsaw-wielding Leatherface.",
            "poster" => "/media/thumbnails/posters/texas-chainsaw.jpg",
            "backdrop" => "/media/thumbnails/backdrops/texas-chainsaw.jpg",
            "video" => "/media/movies/The%20Texas%20Chainsaw%20Massacre.mp4",
            "duration" => 83,
            "categoryId" => "30",
            "published" => 1,
            "year" => 1974,
            "rating" => 7.4,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Horror", "Thriller"],
            "cast_list" => ["Marilyn Burns", "Edwin Neal", "Allen Danziger", "Paul A. Partain"],
            "director" => "Tobe Hooper",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "R"
        ],
        [
            "id" => "39",
            "title" => "Toy Story",
            "slug" => "toy-story",
            "description" => "A cowboy doll is deeply threatened and jealous when a new spaceman figure supplants him as top toy in a boy's room.",
            "poster" => "/media/thumbnails/posters/toy-story.jpg",
            "backdrop" => "/media/thumbnails/backdrops/toy-story.jpg",
            "video" => "/media/movies/Toy.mp4",
            "duration" => 81,
            "categoryId" => "7",
            "published" => 1,
            "year" => 1995,
            "rating" => 8.3,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Animation", "Adventure", "Comedy", "Family"],
            "cast_list" => ["Tom Hanks", "Tim Allen", "Don Rickles", "Jim Varney"],
            "director" => "John Lasseter",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "G"
        ],
        [
            "id" => "40",
            "title" => "Toy Story 2",
            "slug" => "toy-story-2",
            "description" => "When Woody is stolen by a toy collector, Buzz and his friends embark on a daring rescue mission to save him before he is shipped to a museum in Japan.",
            "poster" => "/media/thumbnails/posters/toy-story-2.jpg",
            "backdrop" => "/media/thumbnails/backdrops/toy-story-2.jpg",
            "video" => "/media/movies/Toy-story-2.mkv",
            "duration" => 92,
            "categoryId" => "7",
            "published" => 1,
            "year" => 1999,
            "rating" => 7.9,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Animation", "Adventure", "Comedy", "Family"],
            "cast_list" => ["Tom Hanks", "Tim Allen", "Joan Cusack", "Kelsey Grammer"],
            "director" => "John Lasseter",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "G"
        ],
        [
            "id" => "41",
            "title" => "Transformers Age of Extinction",
            "slug" => "transformers-age-of-extinction",
            "description" => "When humanity allies with a bounty hunter in pursuit of Optimus Prime, the Autobots turn to a mechanic and his daughter for help.",
            "poster" => "/media/thumbnails/posters/transformers-age.jpg",
            "backdrop" => "/media/thumbnails/backdrops/transformers-age.jpg",
            "video" => "/media/movies/Transformers%20Age%20of%20Extinction.mp4",
            "duration" => 165,
            "categoryId" => "1",
            "published" => 1,
            "year" => 2014,
            "rating" => 5.6,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Action", "Adventure", "Sci-Fi"],
            "cast_list" => ["Mark Wahlberg", "Stanley Tucci", "Kelsey Grammer", "Nicola Peltz"],
            "director" => "Michael Bay",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ],
        [
            "id" => "42",
            "title" => "Transformers One",
            "slug" => "transformers-one",
            "description" => "The untold origin story of Optimus Prime and Megatron, who were once brothers-in-arms but became sworn enemies.",
            "poster" => "/media/thumbnails/posters/transformers-one.jpg",
            "backdrop" => "/media/thumbnails/backdrops/transformers-one.jpg",
            "video" => "/media/movies/Transformers%20One.mp4",
            "duration" => 104,
            "categoryId" => "1",
            "published" => 1,
            "year" => 2024,
            "rating" => 7.6,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Animation", "Action", "Adventure", "Sci-Fi"],
            "cast_list" => ["Chris Hemsworth", "Brian Tyree Henry", "Scarlett Johansson", "Keegan-Michael Key"],
            "director" => "Josh Cooley",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG"
        ],
        [
            "id" => "43",
            "title" => "Tucker And Dale Vs Evil",
            "slug" => "tucker-and-dale-vs-evil",
            "description" => "Two well-meaning hillbillies are mistaken for killers by a group of college students, leading to a hilarious series of misunderstandings and accidents.",
            "poster" => "/media/thumbnails/posters/tucker-dale.jpg",
            "backdrop" => "/media/thumbnails/backdrops/tucker-dale.jpg",
            "video" => "/media/movies/Tucker%20And%20Dale%20Vs%20Evil.mp4",
            "duration" => 89,
            "categoryId" => "4",
            "published" => 1,
            "year" => 2010,
            "rating" => 7.5,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Comedy", "Horror"],
            "cast_list" => ["Tyler Labine", "Alan Tudyk", "Katrina Bowden", "Jesse Moss"],
            "director" => "Eli Craig",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "R"
        ],
        [
            "id" => "44",
            "title" => "Yes Man 2008",
            "slug" => "yes-man-2008",
            "description" => "A man who has been avoiding life's responsibilities is challenged to say 'yes' to every opportunity that comes his way.",
            "poster" => "/media/thumbnails/posters/yes-man.jpg",
            "backdrop" => "/media/thumbnails/backdrops/yes-man.jpg",
            "video" => "/media/movies/Yes-Man-2008.mp4",
            "duration" => 104,
            "categoryId" => "4",
            "published" => 1,
            "year" => 2008,
            "rating" => 6.8,
            "featured" => 0,
            "badge" => "",
            "genres" => ["Comedy", "Romance"],
            "cast_list" => ["Jim Carrey", "Zooey Deschanel", "Bradley Cooper", "John Michael Higgins"],
            "director" => "Peyton Reed",
            "country" => "USA",
            "language" => "English",
            "content_rating" => "PG-13"
        ]
    ];
    
    // Prepare insert statement
    $stmt = $db->prepare("
        INSERT OR REPLACE INTO movies (
            id, title, slug, description, poster, backdrop, video,
            duration, category_id, published, created_at,
            year, rating, featured, badge,
            genres, cast_list, director, country, language, content_rating
        ) VALUES (
            :id, :title, :slug, :description, :poster, :backdrop, :video,
            :duration, :category_id, :published, :created_at,
            :year, :rating, :featured, :badge,
            :genres, :cast_list, :director, :country, :language, :content_rating
        )
    ");
    
    $count = 0;
    $now = date('Y-m-d H:i:s');
    
    foreach ($movies as $movie) {
        $stmt->execute([
            ':id' => $movie['id'],
            ':title' => $movie['title'],
            ':slug' => $movie['slug'],
            ':description' => $movie['description'],
            ':poster' => $movie['poster'],
            ':backdrop' => $movie['backdrop'],
            ':video' => $movie['video'],
            ':duration' => $movie['duration'],
            ':category_id' => $movie['categoryId'],
            ':published' => $movie['published'],
            ':created_at' => $now,
            ':year' => $movie['year'],
            ':rating' => $movie['rating'],
            ':featured' => $movie['featured'],
            ':badge' => $movie['badge'],
            ':genres' => json_encode($movie['genres'] ?? []),
            ':cast_list' => json_encode($movie['cast_list'] ?? []),
            ':director' => $movie['director'] ?? '',
            ':country' => $movie['country'] ?? 'USA',
            ':language' => $movie['language'] ?? 'English',
            ':content_rating' => $movie['content_rating'] ?? 'PG-13'
        ]);
        $count++;
    }
    
    echo json_encode([
        'success' => true,
        'message' => "Successfully imported $count movies",
        'count' => $count
    ]);
    
} catch (PDOException $e) {
    http_response_code(500);
    echo json_encode([
        'error' => 'Database error: ' . $e->getMessage()
    ]);
}
?>