<?php
// Enable CORS
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: GET, POST, OPTIONS");
header("Access-Control-Allow-Headers: Content-Type, Authorization");
header("Content-Type: application/json");

// Handle preflight requests
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit();
}

// All movies from your directory
$movies = [
    [
        "id" => "1",
        "title" => "Black Widow 2021",
        "slug" => "black-widow-2021",
        "description" => "Natasha Romanoff confronts her dark past as she faces a conspiracy that threatens the world.",
        "poster" => "/media/thumbnails/black-widow.jpg",
        "background" => "/media/thumbnails/black-widow.jpg",
        "video" => "/media/movies/Black-Widow-2021.mp4",
        "duration" => 134,
        "categoryId" => "1",
        "published" => true,
        "year" => 2021,
        "rating" => 7.3,
        "featured" => true,
        "badge" => "Action Thriller"
    ],
    [
        "id" => "2",
        "title" => "Blue Beetle 2023",
        "slug" => "blue-beetle-2023",
        "description" => "A teenager finds an alien scarab that gives him a powerful exoskeleton suit.",
        "poster" => "/media/thumbnails/blue-beetle.jpg",
        "background" => "/media/thumbnails/blue-beetle.jpg",
        "video" => "/media/movies/Blue-Beetle-2023.mp4",
        "duration" => 127,
        "categoryId" => "1",
        "published" => true,
        "year" => 2023,
        "rating" => 6.5,
        "featured" => false
    ],
    [
        "id" => "3",
        "title" => "Casino Royale",
        "slug" => "casino-royale",
        "description" => "James Bond's first mission as 007 takes him to Montenegro to stop a terrorist financier.",
        "poster" => "/media/thumbnails/casino.jpg",
        "background" => "/media/thumbnails/casino.jpg",
        "video" => "/media/movies/Casino-Royale.mp4",
        "duration" => 144,
        "categoryId" => "2",
        "published" => true,
        "year" => 2006,
        "rating" => 8.0,
        "featured" => false
    ],
    [
        "id" => "4",
        "title" => "Chef 2014",
        "slug" => "chef-2014",
        "description" => "A chef quits his job to start a food truck business and reconnect with his family.",
        "poster" => "/media/thumbnails/Chef_2014.jpg",
        "background" => "/media/thumbnails/Chef_2014.jpg",
        "video" => "/media/movies/Chef-2014.mp4",
        "duration" => 114,
        "categoryId" => "4",
        "published" => true,
        "year" => 2014,
        "rating" => 7.3,
        "featured" => false
    ],
    [
        "id" => "5",
        "title" => "Equalizer",
        "slug" => "equalizer",
        "description" => "A retired black ops operative uses his skills to protect the innocent.",
        "poster" => "/media/thumbnails/The_Equalizer.jpg",
        "background" => "/media/thumbnails/The_Equalizer.jpg",
        "video" => "/media/movies/equalizer.mp4",
        "duration" => 132,
        "categoryId" => "6",
        "published" => true,
        "year" => 2014,
        "rating" => 7.2,
        "featured" => false
    ],
    [
        "id" => "6",
        "title" => "I Robot",
        "slug" => "i-robot",
        "description" => "In 2035, a detective investigates a crime that points to a robot's involvement.",
        "poster" => "/media/thumbnails/robot.jpg",
        "background" => "/media/thumbnails/robot.jpg",
        "video" => "/media/movies/i-robot.mp4",
        "duration" => 115,
        "categoryId" => "23",
        "published" => true,
        "year" => 2004,
        "rating" => 7.1,
        "featured" => false
    ],
    [
        "id" => "7",
        "title" => "Joker 2019",
        "slug" => "joker-2019",
        "description" => "A failed comedian descends into madness and becomes a violent revolutionary.",
        "poster" => "/media/thumbnails/joker.jpg",
        "background" => "/media/thumbnails/joker.jpg",
        "video" => "/media/movies/Joker-2019.mp4",
        "duration" => 122,
        "categoryId" => "1",
        "published" => true,
        "year" => 2019,
        "rating" => 8.4,
        "featured" => true,
        "badge" => "Award-Winning Drama"
    ],
    [
        "id" => "8",
        "title" => "Julie and Julia",
        "slug" => "julie-and-julia",
        "description" => "A young woman blogs about her journey cooking Julia Child's recipes.",
        "poster" => "/media/thumbnails/julie.png",
        "background" => "/media/thumbnails/julie.png",
        "video" => "/media/movies/Julie-and-Julia.mp4",
        "duration" => 123,
        "categoryId" => "4",
        "published" => true,
        "year" => 2009,
        "rating" => 7.0,
        "featured" => false
    ],
    [
        "id" => "9",
        "title" => "Legend",
        "slug" => "legend",
        "description" => "The story of the notorious Kray twins, the most infamous gangsters in London.",
        "poster" => "/media/thumbnails/legend.jpg",
        "background" => "/media/thumbnails/legend.jpg",
        "video" => "/media/movies/Legend.mp4",
        "duration" => 132,
        "categoryId" => "3",
        "published" => true,
        "year" => 2015,
        "rating" => 6.9,
        "featured" => false
    ],
    [
        "id" => "10",
        "title" => "LOL 01",
        "slug" => "lol-01",
        "description" => "A collection of fun and entertaining comedy sketches.",
        "poster" => "/media/thumbnails/LOL01.jpg",
        "background" => "/media/thumbnails/LOL01.jpg",
        "video" => "/media/movies/LOL-01.mp4",
        "duration" => 10,
        "categoryId" => "4",
        "published" => true,
        "year" => 2026,
        "rating" => 5.0,
        "featured" => false
    ],
    [
        "id" => "11",
        "title" => "LOL 02",
        "slug" => "lol-02",
        "description" => "More hilarious comedy sketches for your entertainment.",
        "poster" => "/media/thumbnails/LOL02.jpg",
        "background" => "/media/thumbnails/LOL02.jpg",
        "video" => "/media/movies/LOL-02.mp4",
        "duration" => 8,
        "categoryId" => "4",
        "published" => true,
        "year" => 2026,
        "rating" => 5.0,
        "featured" => false
    ],
    [
        "id" => "12",
        "title" => "LOL 03",
        "slug" => "lol-03",
        "description" => "Comedy sketches that will make you laugh out loud.",
        "poster" => "/media/thumbnails/LOL03.jpg",
        "background" => "/media/thumbnails/LOL03.jpg",
        "video" => "/media/movies/LOL-03.mp4",
        "duration" => 12,
        "categoryId" => "4",
        "published" => true,
        "year" => 2026,
        "rating" => 5.0,
        "featured" => false
    ],
    [
        "id" => "13",
        "title" => "LOL 04",
        "slug" => "lol-04",
        "description" => "Short comedy clips for quick entertainment.",
        "poster" => "/media/thumbnails/LOL04.jpg",
        "background" => "/media/thumbnails/LOL04.jpg",
        "video" => "/media/movies/LOL-04.mp4",
        "duration" => 7,
        "categoryId" => "4",
        "published" => true,
        "year" => 2026,
        "rating" => 5.0,
        "featured" => false
    ],
    [
        "id" => "14",
        "title" => "LOL 05",
        "slug" => "lol-05",
        "description" => "More funny moments and comedy sketches.",
        "poster" => "/media/thumbnails/LOL05.jpg",
        "background" => "/media/thumbnails/LOL05.jpg",
        "video" => "/media/movies/LOL-05.mp4",
        "duration" => 6,
        "categoryId" => "4",
        "published" => true,
        "year" => 2026,
        "rating" => 5.0,
        "featured" => false
    ],
    [
        "id" => "15",
        "title" => "LOL 06",
        "slug" => "lol-06",
        "description" => "The final collection of comedy sketches.",
        "poster" => "/media/thumbnails/LOL06.jpg",
        "background" => "/media/thumbnails/LOL06.jpg",
        "video" => "/media/movies/LOL-06.mp4",
        "duration" => 9,
        "categoryId" => "4",
        "published" => true,
        "year" => 2026,
        "rating" => 5.0,
        "featured" => false
    ],
    [
        "id" => "16",
        "title" => "Martian",
        "slug" => "martian",
        "description" => "An astronaut is stranded on Mars and must survive until rescue.",
        "poster" => "/media/thumbnails/martian.jpg",
        "background" => "/media/thumbnails/martian.jpg",
        "video" => "/media/movies/Martian.mp4",
        "duration" => 144,
        "categoryId" => "23",
        "published" => true,
        "year" => 2015,
        "rating" => 8.0,
        "featured" => false
    ],
    [
        "id" => "17",
        "title" => "Moana 2",
        "slug" => "moana-2",
        "description" => "Moana journeys to the far seas of Oceania after receiving a call from her ancestors.",
        "poster" => "/media/thumbnails/moana-2.jpg",
        "background" => "/media/thumbnails/moana-2.jpg",
        "video" => "/media/movies/Moana2.mp4",
        "duration" => 120,
        "categoryId" => "1",
        "published" => true,
        "year" => 2024,
        "rating" => 8.0,
        "featured" => true,
        "badge" => "Animated Adventure"
    ],
    [
        "id" => "18",
        "title" => "Pearl Harbor",
        "slug" => "pearl-harbor",
        "description" => "Two pilots fall in love with the same nurse during the attack on Pearl Harbor.",
        "poster" => "/media/thumbnails/pearl-harbor.jpg",
        "background" => "/media/thumbnails/pearl-harbor.jpg",
        "video" => "/media/movies/Pearl-Harbor.mp4",
        "duration" => 183,
        "categoryId" => "3",
        "published" => true,
        "year" => 2001,
        "rating" => 6.2,
        "featured" => false
    ],
    [
        "id" => "19",
        "title" => "Pirates",
        "slug" => "pirates",
        "description" => "A group of pirates search for treasure while navigating treacherous waters.",
        "poster" => "/media/thumbnails/pirates.jpg",
        "background" => "/media/thumbnails/pirates.jpg",
        "video" => "/media/movies/Pirates.mp4",
        "duration" => 120,
        "categoryId" => "3",
        "published" => true,
        "year" => 2003,
        "rating" => 7.0,
        "featured" => false
    ],
    [
        "id" => "20",
        "title" => "Scare 01",
        "slug" => "scare-01",
        "description" => "A terrifying horror experience that will keep you on edge.",
        "poster" => "/media/thumbnails/scare01.jpg",
        "background" => "/media/thumbnails/scare01.jpg",
        "video" => "/media/movies/scare01.mp4",
        "duration" => 5,
        "categoryId" => "30",
        "published" => true,
        "year" => 2026,
        "rating" => 4.5,
        "featured" => false
    ],
    [
        "id" => "21",
        "title" => "Scare 02",
        "slug" => "scare-02",
        "description" => "More horror and suspense in this chilling installment.",
        "poster" => "/media/thumbnails/scare02.jpg",
        "background" => "/media/thumbnails/scare02.jpg",
        "video" => "/media/movies/scare02.mp4",
        "duration" => 8,
        "categoryId" => "30",
        "published" => true,
        "year" => 2026,
        "rating" => 4.5,
        "featured" => false
    ],
    [
        "id" => "22",
        "title" => "Scare 03",
        "slug" => "scare-03",
        "description" => "The terror continues with more jump scares and suspense.",
        "poster" => "/media/thumbnails/scare03.jpg",
        "background" => "/media/thumbnails/scare03.jpg",
        "video" => "/media/movies/scare03.mp4",
        "duration" => 7,
        "categoryId" => "30",
        "published" => true,
        "year" => 2026,
        "rating" => 4.5,
        "featured" => false
    ],
    [
        "id" => "23",
        "title" => "Scare 04",
        "slug" => "scare-04",
        "description" => "Horror anthology that will send chills down your spine.",
        "poster" => "/media/thumbnails/scare04.jpg",
        "background" => "/media/thumbnails/scare04.jpg",
        "video" => "/media/movies/scare04.mp4",
        "duration" => 6,
        "categoryId" => "30",
        "published" => true,
        "year" => 2026,
        "rating" => 4.5,
        "featured" => false
    ],
    [
        "id" => "24",
        "title" => "Scare 05",
        "slug" => "scare-05",
        "description" => "The fear intensifies in this horror collection.",
        "poster" => "/media/thumbnails/scare05.jpg",
        "background" => "/media/thumbnails/scare05.jpg",
        "video" => "/media/movies/scare05.mp4",
        "duration" => 9,
        "categoryId" => "30",
        "published" => true,
        "year" => 2026,
        "rating" => 4.5,
        "featured" => false
    ],
    [
        "id" => "25",
        "title" => "Scare 06",
        "slug" => "scare-06",
        "description" => "The final chapter in the horror series.",
        "poster" => "/media/thumbnails/scare06.jpg",
        "background" => "/media/thumbnails/scare06.jpg",
        "video" => "/media/movies/scare06.mp4",
        "duration" => 10,
        "categoryId" => "30",
        "published" => true,
        "year" => 2026,
        "rating" => 4.5,
        "featured" => false
    ],
    [
        "id" => "26",
        "title" => "Spider-Man 3",
        "slug" => "spider-man-3",
        "description" => "Peter Parker faces his greatest challenge yet as multiple villains emerge.",
        "poster" => "/media/thumbnails/spider.jpg",
        "background" => "/media/thumbnails/spider.jpg",
        "video" => "/media/movies/Spider-Man-3.mp4",
        "duration" => 139,
        "categoryId" => "1",
        "published" => true,
        "year" => 2007,
        "rating" => 6.3,
        "featured" => false
    ],
    [
        "id" => "27",
        "title" => "Spider-Man Into The Spider-Verse",
        "slug" => "spider-man-into-the-spider-verse",
        "description" => "Miles Morales becomes the new Spider-Man and meets other spider-heroes.",
        "poster" => "/media/thumbnails/spiderverse.jpg",
        "background" => "/media/thumbnails/spiderverse.jpg",
        "video" => "/media/movies/Spider-Man-Into-The-Spider-Verse.mp4",
        "duration" => 117,
        "categoryId" => "1",
        "published" => true,
        "year" => 2018,
        "rating" => 8.4,
        "featured" => true,
        "badge" => "Animated Masterpiece"
    ],
    [
        "id" => "28",
        "title" => "The Amazing Spider-Man 2",
        "slug" => "the-amazing-spider-man-2",
        "description" => "Spider-Man battles Electro and faces his greatest enemy.",
        "poster" => "/media/thumbnails/amazing-spiderman2.jpg",
        "background" => "/media/thumbnails/amazing-spiderman2.jpg",
        "video" => "/media/movies/The-Amazing-Spider-Man-2.mp4",
        "duration" => 142,
        "categoryId" => "1",
        "published" => true,
        "year" => 2014,
        "rating" => 6.6,
        "featured" => false
    ],
    [
        "id" => "29",
        "title" => "The Hunger Games",
        "slug" => "the-hunger-games",
        "description" => "In a dystopian future, a girl volunteers to compete in a deadly tournament.",
        "poster" => "/media/thumbnails/hunger-games.jpg",
        "background" => "/media/thumbnails/hunger-games.jpg",
        "video" => "/media/movies/The-Hunger-Games.mp4",
        "duration" => 142,
        "categoryId" => "2",
        "published" => true,
        "year" => 2012,
        "rating" => 7.2,
        "featured" => false
    ],
    [
        "id" => "30",
        "title" => "The Intern",
        "slug" => "the-intern",
        "description" => "A 70-year-old intern helps a young CEO navigate the world of e-commerce.",
        "poster" => "/media/thumbnails/the-intern.jpg",
        "background" => "/media/thumbnails/the-intern.jpg",
        "video" => "/media/movies/The-Intern.mp4",
        "duration" => 121,
        "categoryId" => "4",
        "published" => true,
        "year" => 2015,
        "rating" => 7.1,
        "featured" => false
    ],
    [
        "id" => "31",
        "title" => "The Longest Yard",
        "slug" => "the-longest-yard",
        "description" => "A former football star leads a team of inmates in a game against the guards.",
        "poster" => "/media/thumbnails/Longest-yard.jpg",
        "background" => "/media/thumbnails/Longest-yard.jpg",
        "video" => "/media/movies/The-Longest-Yard.mp4",
        "duration" => 113,
        "categoryId" => "4",
        "published" => true,
        "year" => 2005,
        "rating" => 6.4,
        "featured" => false
    ],
    [
        "id" => "32",
        "title" => "The Marvels",
        "slug" => "the-marvels",
        "description" => "Carol Danvers teams up with other heroes to face a new threat.",
        "poster" => "/media/thumbnails/the-marvels.jpg",
        "background" => "/media/thumbnails/the-marvels.jpg",
        "video" => "/media/movies/The-Marvels.mp4",
        "duration" => 105,
        "categoryId" => "1",
        "published" => true,
        "year" => 2023,
        "rating" => 6.1,
        "featured" => false
    ],
    [
        "id" => "33",
        "title" => "Yes Man 2008",
        "slug" => "yes-man-2008",
        "description" => "A man says yes to everything and transforms his life.",
        "poster" => "/media/thumbnails/yes-man.jpg",
        "background" => "/media/thumbnails/yes-man.jpg",
        "video" => "/media/movies/Yes-Man-2008.mp4",
        "duration" => 104,
        "categoryId" => "4",
        "published" => true,
        "year" => 2008,
        "rating" => 6.8,
        "featured" => false
    ]
];

// Return the movies
echo json_encode([
    'success' => true,
    'movies' => $movies
]);
?>